apiVersion: v1
kind: Service
metadata:
  name: autocont
  namespace: namespace-workflow-1688625052800
spec:
  type: LoadBalancer
  selector:
    app: autocont
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000